feat: 🎸 fix install package

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -51,13 +51,17 @@ runs:
       with:
         python-version: '3.10'
         cache: 'pip'
-        cache-dependency-path: |
-          requirements.txt
 
     - name: Install dependencies
       shell: bash
       run: |
-          pip install -r requirements.txt
+        python -m pip install --upgrade pip
+        if [ -f ${{ github.action_path }}/requirements.txt ]; then
+          pip install -r ${{ github.action_path }}/requirements.txt
+        else
+          echo "Error: requirements.txt not found in ${{ github.action_path }}"
+          exit 1
+        fi
 
     - name: Run code review
       shell: bash
@@ -72,4 +76,10 @@ runs:
         INPUT_EXCLUDE: ${{ inputs.INPUT_EXCLUDE }}
         HUMAN_LANGUAGE: ${{ inputs.HUMAN_LANGUAGE }}
         PRIMARY_MODEL: ${{ inputs.PRIMARY_MODEL }}
-      run: python3.10 -m src.main ${{ github.action_path }}/src/main.py
+      run: |
+        if [ -f ${{ github.action_path }}/src/main.py ]; then
+          python -m src.main ${{ github.action_path }}/src/main.py
+        else
+          echo "Error: main.py not found in ${{ github.action_path }}/src/"
+          exit 1
+        fi
